#!/bin/bash

mluv() {
	echo "$1" | festival --tts
}

h=/home/pi
log=log_zaloha_fotak

echo "proběhlo" > $log

#přepne zvuk
amixer cset numid=3 1

# připojení disků
$h/skritek_pomocnik/slartibartfast Fotky 2> $h/skritek_pomocnik/$log
if test -d $h/Slartibartfast/Fotky/Kouzelna_skrinka; then
	mount /dev/disk/by-id/usb-CASIO_COMPUTER_CASIO_QV_DIGITAL_1013641227147740-part1 /home/pi/Kouzelna_skrinka/ 2> $h/skritek_pomocnik/$log
	if test -d $h/Kouzelna_skrinka/DCIM;then
		echo "Synchronizuji na externí úložiště."
		mluv "Synchronization on external harddrive."
	else
		echo "Nepovedlo se připojit fotoaparát! Více v logu."
		mluv "Can't mount digital camera. See log"
		exit 1
	fi
else
	echo "Nepovedlo se připojit externí úložiště! Více v logu."
	mluv "Can't mount external harddrive. See the log"
	exit 1
fi

# kopírování
cp $h/Kouzelna_skrinka/DCIM/100CASIO/* $h/Slartibartfast/Fotky/Kouzelna_skrinka -u

# odpojení disků
$h/skritek_pomocnik/slartibartfast Fotky odpoj 2> $h/skritek_pomocnik/$log
umount /dev/disk/by-id/usb-CASIO_COMPUTER_CASIO_QV_DIGITAL_1013641227147740-part1 2> $h/skritek_pomocnik/$log

povedlose=1
if test -d $h/Slartibartfast/Fotky/Kouzelna_skrinka; then
	echo "Synchronizace provedena, ale nepovedlo se odpojit externí úložiště. Více v logu";
	mluv "Synchronization's OK, but can't remove external harddrive, see log"
	povedlose=0
fi
if test -d $h/Kouzelna_skrinka/DCIM;then
	echo "Synchronizace provedena, ale nepovedlo se odpojit fotoaparát. Více v logu";
	mluv "Synchronization's OK, but can't remove digital camera, see log"
	povedlose=0
fi

if test -n $povedlose; then
	echo "Synchronizace provedena."
	mluv "Succes, you can safety remove devices"
fi

#přepne zvuk
amixer cset numid=3 2

if test -z j$povedlose;then
	exit 1
fi

exit 0
